"""
FastAPI application entry point.

Run with:
    uvicorn backend.app.main:app --reload
"""

import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.app.api.routes.query import router as query_router

# ── Logging ────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)

# ── App ────────────────────────────────────────────────────────────────
app = FastAPI(
    title="RAG Assistant API",
    description=(
        "A Retrieval-Augmented Generation assistant that answers questions "
        "using PDF documents indexed into ChromaDB and generated by Ollama (llama3)."
    ),
    version="1.0.0",
)

# Allow any frontend to call the API during development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Routes ─────────────────────────────────────────────────────────────
app.include_router(query_router)


@app.get("/", tags=["health"])
async def root():
    """Health-check / welcome endpoint."""
    return {
        "status": "ok",
        "message": "RAG Assistant API is running.",
    }
